### ISSUE TITLE
pipenv -> poetry

### ISSUE THREAD

**Issue by kdutia** [TheScienceMuseum/heritage-connector#111]
move to [poetry](https://python-poetry.org/) because pipenv is slow/keep having to reset graph

**Comment by kdutia** [comment]
Closing because poetry dependency resolution hangs for an infinite time (worse performance than pipenv). Poetry issues say it's a Python problem. 

see branch `pipenv_to_poetry` for the Poetry pyproject.toml file

fyi @jamieu

**Comment by jamieu** [comment]
Oh well you tried :-(
