### ISSUE TITLE
test KG embeddings with pykeen

### ISSUE THREAD

**Issue by kdutia** [TheScienceMuseum/heritage-connector#162]
using pykeen https://github.com/pykeen/pykeen

---

Between ComplEx, DistMult, TransE, RotatE. ComplEx and RotatE produce complex-valued embeddings, so need to figure out whether we can still use dim reduction to plot them. 

- ablation study: https://arxiv.org/pdf/2006.13365.pdf
- notebook: https://github.com/pykeen/pykeen/blob/master/notebooks/results_plots/results_plots.ipynb

---

- [x] ~try to plot embeddings for complex-valued models using the notebook above (can be opened in colab)~ tested on some sample data in [this notebook](https://colab.research.google.com/drive/1-fzg9Rq2H8vkECXcsuI6CF2cyszNscBo?usp=sharing). TransE works best for visualisation on this dataset and ComplEx isn't good. 
- [x] ~choose one or two candidate models~ Start with TransE and RotatE as they're from two different families of models, and both use addition (better for visualisation).
- [ ] train models and compare results (using hyperparameter optimisation and tips from ablation study)

**Comment by cthoyt** [comment]
Hi @kdutia please feel free to reach out for support on PyKEEN. Greetings from Germany

**Comment by kdutia** [comment]
Thanks @cthoyt, I'll be revisiting different KG embeddings with literals methods soon then give your library a spin
