### ISSUE TITLE
can we do a direct lookup of object/place/material names on Getty?

### ISSUE THREAD

**Issue by kdutia** [TheScienceMuseum/heritage-connector#45]
geographical: TGN
object names & materials: AAT
---
**TO DO**
- [x] get Getty IDs of object types from Collection
- [x] map Getty IDs to Wikidata IDs
- [x] store mapping of name-Getty-Wikidata somewhere

**Comment by jamieu** [comment]
May be worth thinking of how we abstract this, 

With Getty reconciliation being the one we implement. But leaving the door open for others to add reconciliation modules for the likes of Library of Congress Subject Headings (LCSH) or UK Archival Thesaurus (UKAT) at a later date if they want.

Ideally this would be optional, maybe on a per collection or per field basis ie. part of the import/loader confutation that describe or gives hint to what fields may contain what values ie. 

```
document:
    type: object:
    fields:
        field:
            name: "material" 
             type: "material" 
            clues: "att"
```

Geographical places may be better handled with a more general/generic geo-lookup service?

A good start may be Getty’s own reconciliation service/api..
https://www.getty.edu/research/tools/vocabularies/lod/
https://www.getty.edu/research/tools/vocabularies/obtain/getty_vocabularies_openrefine_tutorial.pdf

There are also some existing Python packages for Getty that may prove useful in this task.
https://github.com/OnroerendErfgoed/skosprovider_getty
https://readthedocs.org/projects/skosprovider-getty/downloads/pdf/latest/

**Comment by kdutia** [comment]
There is an open reconciliation API standard that OpenRefine uses: https://reconciliation-api.github.io/specs/0.1/#structure-of-a-reconciliation-query. 

If we build any reconciliation into the heritage connector (faster, more suited to our needs), we should try to build toward this standard so users can perform the same tasks in OpenRefine if necessary.
